[package]
name = "propbase_coin"
version = "1.0.0"
authors = ["neethu.satheesh"]
upgrade_policy = "immutable"

[addresses]
admin = "0xaada000490412ecbd319f494b9dbfe7a745605aba8a4c8d09b21e4ab1c772862"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
