[package]
name = "propbase_coin"
version = "1.0.0"
authors = ["neethu.satheesh"]

[addresses]
admin = "0xfb70b30790539849987be2c13ee6fbc2b73cc9e4d34722309f56ece20a0a98fc"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
