[package]
name = "propbase_coin_10"
version = "1.0.0"
authors = ["neethu.satheesh"]

[addresses]
admin = "0x1cac17ac868932548f4a85fe3e853a1023a57b7f275d4247e1cded85d40b3c3d"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
