[package]
name = "propbase_coin"
version = "1.0.0"
authors = ["neethu.satheesh"]
upgrade_policy = "immutable"

[addresses]
admin = "0xadminaddress"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
